name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends -o APT::Immediate-Configure=0  \
                python3-pytest

      - name: Run tests
        run: |
            PYTHONPATH=. python3 -m pytest tests/tests.py --capture=no -ra -vv
